### ISSUE TITLE
Issues while loading mods

### ISSUE THREAD

**Issue by Cubiccl** [demodude4u/Java-Factorio-Data-Wrapper#26]
Hello, I found a fue issues while loading various mods, and I think I found the fixes. Hope this helps :)

- **base** may load after some mods. It looks like it should load before as it generated some errors accessing to _data.raw.technology_ for example.
- The **config.lua** file of mods isn't called. I'm not sure if it's mandatory but adding it after initializeSettings() fixed some errors.
- The mod list isn't loaded into lua. Some mods with compatibility will look for a _mod_ array. Creating it before settings.lua seems to fix the issue.

For reference, here are the mods I used for testing:
DyWorld 0.8.6
Afraid of the Dark 1.0.23
FNEI 0.2.7
SpaceMod 0.4.4

**Comment by Bilka2** [comment]
> base may load after some mods. It looks like it should load before as it generated some errors accessing to data.raw.technology for example.

Dependencies in general are not handled at all, so this is kind of expected.
> The config.lua file of mods isn't called. I'm not sure if it's mandatory but adding it after initializeSettings() fixed some errors.

The base game does not load this file, so that sounds more like a broken mod.

> The mod list isn't loaded into lua. Some mods with compatibility will look for a mod array. Creating it before settings.lua seems to fix the issue.

There is not "mod array". There is however a "mods table", I might look at pushing that into the lua state.

**Comment by Bilka2** [comment]
Hey, I fixed the third point with 4657bc00e92530bb38f15ba4e6450d026ccb131b and the first point was moved to #37 as it needs some more investigation (dependencies should work in general, but there are edge cases).
